name: Build Docs

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Set up Cache
      uses: actions/cache@v1
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('Pipfile') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Install Pipenv
      run: pip install pipenv
    - name: Build Site
      run: pipenv install && pipenv run python -m mkdocs build
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@2.0.0
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BRANCH: gh-pages
        FOLDER: site
